Sondo_shopping/Sondo_shopping/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView

from customers import views as user_views
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from Sondo_shopping import views as passwordViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('register/', user_views.register, name='register'),
    #url('^accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),

    path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
                       name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                      template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", passwordViews.password_reset_request, name="password_reset"),


    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    # path("/api/rst-auth/registration/",include("rest_auth.registration.urls")),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sondo_shopping/store/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view
from . import views
from django.urls import path, re_path
from .views import Home,Signup,logout,Cart,Checkout,OrderView
from .middlewares import LoginCheckMiddleware

from .views.home import CommentUpdateView, CommentDeleteView, ProductDetailView

schema_views = get_swagger_view(title='Online Shopping API')
router = DefaultRouter()
router1 = DefaultRouter()
router2 = DefaultRouter()
router3 = DefaultRouter()
router4 = DefaultRouter()

router1.register(r"categories",views.CategoryViewSet,"categories")
router2.register(r"comments",views.CommentViewSet,"comments")
router3.register(r"orders",views.OrderViewSet,"orders")
router4.register(r"products",views.ProductViewSet,"products")
router.register(r"customers",views.CustomerViewSet,"customers")

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('customers/', include(router.urls)),
    path('categories/', include(router1.urls)),
    path('comments/', include(router2.urls)),
    path('orders/', include(router3.urls)),
    path('products/', include(router4.urls)),

    path('api/',schema_views),
    path('search/', Home.as_view(),name='search'),
    path('signup',Signup.as_view(), name='signup'),
    #path('login',Login.as_view(), name='login'),
    re_path(r"^home/$", views.Home.as_view(), name="home"),
    path('logout',LoginCheckMiddleware(logout), name='logout'),
    path('cart',LoginCheckMiddleware(Cart.as_view()), name='cart'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('checkout',LoginCheckMiddleware(Checkout.as_view()), name='checkout'),
    path('order',LoginCheckMiddleware(OrderView.as_view()), name='order'),
    # path('create/<str:content_type>/<int:object_id>/', CommentCreateView.as_view(), name='comment-create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]

Sondo_shopping/store/models/Comment.py
import datetime
from django.db import models
from users.models import User
from django.urls import reverse

from store.models import Product


class Comment(models.Model):
    text = models.TextField(max_length=150)
    date_posted = models.DateTimeField(default=datetime.datetime.now())
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='images/default.png', upload_to='profile_pics')
    product_connected = models.ForeignKey(Product, on_delete=models.CASCADE,default=1)

    def __str__(self):
        return self.text


    def get_absolute_url(self):
        return reverse('product-detail',kwargs={'pk':self.product_connected.id})

Sondo_shopping/store/models/category.py
from django.db import models

class Category(models.Model):
	name = models.CharField(max_length=20)

	def __str__(self):
		return self.name


	@staticmethod
	def getAllCategory():
		return Category.objects.all()

Sondo_shopping/customers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import User
from .models import Customer


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['image','phone']

Sondo_shopping/customers/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, CustomerUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your Account was created Successfully!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'customer.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = CustomerUpdateForm(request.POST, request.FILES, instance=request.user.customer)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account has been updated')
            return redirect('customer')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = CustomerUpdateForm(instance=request.user.customer)

    u_form = UserUpdateForm(instance=request.user)
    p_form = CustomerUpdateForm(instance=request.user.customer)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'customer.html', context)

Sondo_shopping/store/views/cart.py
from django.shortcuts import render, redirect
from django.views import View
from store.models.product import Product

class Cart(View):
    def get(self,request):
        productList = list(request.session.get('cart').keys())
        if request.GET.get('increase'):
            products = request.session.get('')
            print(products)
            pId = request.GET.get('increase')
            products = request.session.get('cart')
            products[pId] += 1
            request.session['cart'] = products

        if request.GET.get('decrease'):
            pId = request.GET.get('decrease')
            products = request.session.get('cart')
            print(products[pId])
            if products[pId] > 1:
                products[pId] -= 1
                request.session['cart'] = products
                productList = list(request.session.get('cart').keys())
            else :
                del products[pId]
                request.session['cart'] = products
                productList = list(request.session.get('cart').keys())


        allProduct = Product.getProductById(productList)
        return render(request,'cart.html',{"allProduct":allProduct})

Sondo_shopping/store/views/checkout.py
from django.shortcuts import render, redirect
from django.views import View
from store.models import Order
from store.models import Customer
from store.models import Product
from store.tasks import OrderEmail


class Checkout(View):
    def get(self, request):
        return redirect('cart')

    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        cart = request.session.get('cart')
        products = Product.getProductById(list(cart.keys()))
        customer = request.session.get('customer')

        for product in products:

            newOrder = Order(
                product=product,
                customer=Customer(id=customer),
                quantity=cart[str(product.id)],
                price=product.price,
                address=address,
                phone=phone,
            )
            newOrder.save()
            print(newOrder.id)

            OrderEmail.delay(order_id=newOrder.id)

        request.session['cart'] = {}
        return redirect('order')

Sondo_shopping/store/views/comment.py
# from django.contrib import messages
# from django.contrib.contenttypes.models import ContentType
# from django.http import HttpResponseRedirect
# from django.views import View
#
# from store.forms import NewCommentForm
#
#
# class CommentCreateView(View):
#
#     @staticmethod
#     def post(request, *args, **kwargs):
#         form = NewCommentForm(request.POST or None)
#         ct = ContentType.objects.get(model=kwargs['content_type'])
#         model = ct.model_class().objects.get(pk=kwargs['object_id'])
#         if form.is_valid():
#             new_comment = form.save(commit=False)
#             new_comment.author = request.user
#             new_comment.text = form.cleaned_data['text']
#             new_comment.content_object = model
#             new_comment.save()
#             return HttpResponseRedirect(model.get_absolute_url())
#         messages.add_message(request, messages.ERROR, 'Не удалось оставить комментарий')
#         return HttpResponseRedirect(model.get_absolute_url())

Sondo_shopping/store/views/home.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView
from customers.models import Customer
from store.forms import NewCommentForm
from store.models import Product, Comment
from store.models import Category




class Home(View):
    def get(self,request):
        if request.user.is_anonymous is not True:
            print(request.user.is_anonymous)
            print(request.user)
            customer = Customer.objects.get(customer=request.user)
            request.session["customer"] = customer.id

        cart = request.session.get('cart')
        categories = Category.getAllCategory()
        products = Product.getAllProduct().order_by('-id')

        if request.GET.get('id'):

            filterProductById = Product.objects.get(id=int(request.GET.get('id')))
            return render(request, 'productDetail.html',{"product":filterProductById,"categories":categories})

        if not cart:
            request.session['cart'] = {}

        if request.GET.get('category_id'):
            filterProduct = Product.getProductByFilter(request.GET['category_id'])
            return render(request, 'home.html',{"products":filterProduct,"categories":categories})

        return render(request, 'home.html',{"products":products,"categories":categories})

    def get_queryset(self):
        '''
        building a dynamic Queryset
        '''
        queryset = Product.objects.all().all().order_by('-date_posted')
        query = self.request.GET.get('q')

        if query:
            queryset = queryset.filter(
                Q(author__username__icontains=query) |
                Q(title__icontains=query) |
                Q(content__icontains=query)
            ).distinct()
        return queryset

    def post(self,request):
        product = request.POST.get('product')

        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(product)
            if quantity:
                cart[product] = quantity+1
            else:
                cart[product] = 1
        else:
            cart = {}
            cart[product] = 1

        print(cart)
        request.session['cart'] = cart
        return redirect('cart')


class ProductDetailView(LoginRequiredMixin,DetailView):
    model = Product
    template_name = 'productDetail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        #user = self.request.session.get('customer')
        data = super().get_context_data(**kwargs)
        comments_connected = Comment.objects.filter(product_connected=self.get_object()).order_by('-date_posted')
        data['comments'] = comments_connected
        #customer = Customer.objects.get(id=user)
        data['form'] = NewCommentForm(instance=self.request.user)
        return data

    def post(self, request, *args, **kwargs):
        print(str(self.request.user) +"  posting a comment")
        customer = Customer.objects.get(customer=self.request.user)
        new_comment = Comment(text=request.POST.get('text'),
                              author=self.request.user,
                              product_connected=self.get_object(),
                              image=customer.image)

        new_comment.save()

        return self.get(self, request, *args, **kwargs)



class CommentUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Comment
    fields = ['text']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False


class CommentDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Comment
    success_url = '/'
    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False

Sondo_shopping/store/views/login.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views import View
from store.models import Customer


class Login(View):
    return_url = None

    def get(self, request):
        Login.return_url = request.GET.get('return_url')
        return render(request, 'registration/login.html')

    def post(self, request):
        userData = request.POST
        customerEmail = Customer.emailExits(userData["email"])
        if customerEmail:
            # user = authenticate(email=customerEmail, password=userData["password"])
            if userData["password"] == customerEmail.password:
                # if user is not None:
                print("Step 2 passed")
                request.session["customer"] = customerEmail
                # request.session["user"]
                # print(userData["email"])
                if Login.return_url:
                    print("Shuuuu")
                    return HttpResponseRedirect(Login.return_url)
                else:
                    print(Login.return_url)
                    Login.return_url = None
                    return redirect('/')
            else:
                print(customerEmail.customer)
                print(customerEmail.password)
                return render(request, 'registration/login.html',
                              {"userData": userData, "error": "Email or password doesn't match"})
        else:

            return render(request, 'registration/login.html',
                          {"userData": userData, "error": "Email or password doesn't match"})


def logout(request):
    request.session.clear()
    return redirect('home')

Sondo_shopping/store/views/order.py
from django.shortcuts import render
from django.views import View
from store.models import Customer
from store.models import Order



class OrderView(View):
    def get(self, request):
        customer_id = Customer.objects.get(customer=self.request.user)
        orders = Order.objects.all()
        print(orders)
        return render(request, 'order.html', {"orders": orders})

Sondo_shopping/store/views/serializerView.py
from rest_framework import viewsets
from customers.models import Customer
from store.models import Category, Product, Order
from store.models.Comment import Comment
from store.serializers import CommentSerializer, CategorySerializer, OrderSerializer, ProductSerializer, \
    CustomerSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    serializer_class = CategorySerializer
    def get_queryset(self):
        return Category.objects.all()

class CommentViewSet(viewsets.ModelViewSet):
    serializer_class = CommentSerializer
    queryset = Comment.objects.prefetch_related('product_connected')
    def get_queryset(self):
        return Comment.objects.all()

class OrderViewSet(viewsets.ModelViewSet):
    serializer_class = OrderSerializer
    def get_queryset(self):
        return Order.objects.all()

class ProductViewSet(viewsets.ModelViewSet):
    serializer_class = ProductSerializer
    def get_queryset(self):
        return Product.objects.all()

class CustomerViewSet(viewsets.ModelViewSet):
    serializer_class = CustomerSerializer
    def get_queryset(self):
        return Customer.objects.all()

Sondo_shopping/store/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <a class="navbar-brand" href="/">Sondos Shopping</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Products</a>
                </li>
            </ul>

                 <form method="get" action="{% url 'search' %}">
             <input type="text" name="q" placeholder="Search Posts" value="{{ request.GET.q }}">

    <input class="btn btn-primary" type="submit" value="Search"/>

    </form>

            <form class="form-inline">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart' %}">Cart
                        <span class="badge badge-info">{{ request.session.cart.keys|length }}</span>
                        </a>
                    </li>
                    {% if request.session.customer %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'order' %}">Order</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Profile</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                       <a class="nav-item nav-link" href="{% url 'signup' %}">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </form>
        </div>
    </nav>
    {% if signupSuccess %}
        {{ signupSuccess }}
    {% endif %}

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

Sondo_shopping/store/templates/cart.html
{% extends 'base.html' %}
{% load cart %}
{% block title %} Sondos shopping | Cart {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        {% if request.session.cart %}
        <h1 class="font-weight-light">Cart</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>S.no</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Actions</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
            	{% for product in allProduct %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img height="80px" width="100px" src="{{ product.image.url }}" alt=""></td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price|currency }}</td>
                    <td>{{ product|cart_quantity:request.session.cart }}</td>
                    <td>
                    	<a href="cart?increase={{ product.id }}" class="btn btn-sm btn-warning">+</a>
                        <a href="cart?decrease={{ product.id }}" class="btn btn-sm btn-danger">-</a>
                    </td>
                    <th>{{ product|price_subtotal:request.session.cart|currency }}</th>

                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
            	<tr>
            		<td colspan="5"></td>
            		<td colspan="1"><strong>Total : </strong></td>
            		<td>{{ allProduct|price_total:request.session.cart|currency }}</td>
            	</tr>
            </tfoot>
        </table>
    </div>
    <hr>
    <div class="float-right">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#exampleModalCenter">
          Checkout
        </button>
    </div>
    {% else %}
        <h1 class="font-weight-light text-center">No cart added</h1>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="/checkout" method="post">
                {% csrf_token %}
                 <div class="form-group">
                    <label for="address">Address</label>
                    <input name="address" type="text" class="form-control" id="address" placeholder="Enter address">
                </div>
                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input name="phone" type="number" class="form-control" id="phone" placeholder="Enter phone">
                </div>
                <div class="float-right">
                    <input type="submit" value="Confirm" class="btn btn-success">
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>

</div>
{% endblock %}

Sondo_shopping/store/templates/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-info">
An Email has been Sent On how to Reset your Password
</div>

{% endblock content %}

Sondo_shopping/store/templates/productDetail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load cart %}
{% block title %} Sondos Shopping | Product {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2 mb-3">
            <ul class="list-group">
                <li class="list-group-item active bg-secondary border-0"><a style="text-decoration:none; color:white;" href="/">All Category</a></li>
            	{% for category in categories %}
                <li class="list-group-item"><a style="text-decoration:none; color:black;" href="/?category_id={{ category.id }}">{{ category.name }}</a></li>
				{% endfor %}
            </ul>
        </div>
        <div class="col-md-10">
            	{% if product  %}
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ product.image.url }}" height="100%;" width="250px" alt="{{ product.name }}">
                                </div>
                                <div class="col-md-8">
                                    <div>
                                        <h1 class="font-weight-light">{{ product.name }}</h1>
                                        <h4 class="font-weight-light">Price: <strong>{{ product.price|currency }}</strong></h4>
                                         <form action="/#{{ product.id }}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" value="{{ product.id }}" name="product">
                                            {% if product|is_in_cart:request.session.cart %}
                                            <a class="btn btn-warning" href="/cart">Go to cart </a>
                                            {% else %}
                                            <input class="btn btn-primary" type="submit" value="Add to cart">
                                            {% endif %}
                                        </form>
                                        <p class="mt-2"><strong>Description: </strong> {{ product.description }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
        </div>
    </div>
</div>


    <div class="row pl-3" id="comments-list">
        <div class="col-12 col-md-6 pl-0">
         <h3 class="white-important mb-3">
             Comments
         </h3>

        {% for comment in comments %}

       <article class="media content-section">
       <div class="col-md-12 mt-3 mb-3">
           <p>
           <img
                         class="rounded-circle mr-2"
                          style="width: 35px; height: 35px;"
                          src="{{ comment.image.url }}">

           <strong>{{ comment.author}}</strong> | <small>date: {{ comment.date_posted | date:"H:i l, d.m.y" }}</small></p>
           <p>{{ comment.text }}</p>
       </div>

{#                <div style="width: 100%; word-break: break-all;" class="hovered-tweet-comment-in">#}
{#                <div class="pb-2 row m-0" style="width: 100%; margin-right: 2px !important;">#}
{#                   <div#}
{#                           style="padding-left: 0px !important;"#}
{#                           class="col-8 no-padding d-flex align-items-center">#}
{#                       <img#}
{#                           class="rounded-circle mr-2"#}
{#                           style="width: 35px; height: 35px;"#}
{#                           src="{{ comment.author.image.url }}">#}
{#                       <a>#}
{#                           {{ comment.author }}#}
{#                       </a>#}
{#                   </div>#}

                            {% if comment.author.username == user.username %}

                                <div class="topright">
<object align="right">
            <div class="dropdown">
  <button data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
</svg>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'comment-update' comment.id %}">Edit</a>
    <a class="dropdown-item" href="{% url 'comment-delete' comment.id %}">delete</a>

  </div>
</div>
</object>
</div>


        {% endif %}


</article>
        {% endfor %}

</div>

     {% if user is not None %}
            <div class="col-12 col-md-6 pl-0 pl-md-3 pr-3">
                <h3 class="white-important mb-3">
                    Add a comment
                </h3>
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form | crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-primary" id='send-comment' type="submit">Submit comment</button>
                    </div>
                </form>
            </div>
        {% endif %}
 </div>

    <script>

     var ws_scheme = window.location.protocol === "https:" ? "wss://" : "ws://";
     const commentsSocket = new WebSocket(
         ws_scheme
         + window.location.host
         + '/product/'
         + "{{ product.id }}"
         + "/"
     )

     commentsSocket.onmessage = function (e){

         const data = JSON.parse(e.data)

         commentslist = document.getElementById('comments-list')
         commentslist.insertAdjacentHTML(
             'beforeend',
             '<div class="col-md-12 mt-3 mb-3">\n' +
             '<p><img class="rounded-circle mr-2" style="width: 35px; height: 35px;" src=" ' + data['message']['image'] + '"> \n' +

           '<strong>' + data['message']['author'] + ' </strong> | <small>date: ' + data['message']['date_posted'] + '</small></p>\n'+
           '<p>' + data['message']['text'] + '</p>\n' +
           '</div>\n'
         )
      };

     document.querySelector('#send-comment').onclick = function (e){
         e.preventDefault()
         const message = document.querySelector('#id_text');
         const text = message.value


         console.log("Channels..");
         commentsSocket.send(JSON.stringify({
             'text': text
         }));
         message.value = '';
      }
</script>

{% endblock %}
{#{% block js %}#}


{#{% endblock js %}#}